name: alacritty
adopt-info: alacritty

base: core20
grade: stable
confinement: classic

apps:
    alacritty:
        command: bin/alacritty
        common-id: io.alacritty.Alacritty
        desktop: usr/share/applications/Alacritty.desktop
        environment:
            LC_ALL: C.UTF-8
            XKB_CONFIG_ROOT: $SNAP/usr/share/X11/xkb
            XCURSOR_PATH: $SNAP/usr/share/icons
            XLOCALEDIR: $SNAP/usr/share/X11/locale
            LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri
            LIBGL_DRIVERS_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri
            LIBVA_DRIVERS_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri
            __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d

parts:
    mesa:
        plugin: nil
        stage-packages:
            - libglu1-mesa
            - libgl1-mesa-dri
            - libgl1-mesa-glx
            - libegl-mesa0
            - libegl1
            - libegl1-mesa
        build-attributes:
            - no-patchelf

    alacritty:
        plugin: rust
        source: https://github.com/alacritty/alacritty.git
        source-tag: v0.7.1
        parse-info:
            - extra/linux/io.alacritty.Alacritty.appdata.xml
        rust-path:
            - alacritty
        build-packages:
            - cmake
            - pkg-config
            - libfreetype6-dev
            - libfontconfig1-dev
            - libxcb-xfixes0-dev
            - python3
            - libegl1-mesa-dev # necessary for nvidia users on wayland
        stage-packages:
            - libfontconfig1
            - libfreetype6
            - libpng16-16
        override-build: |
            version=$(git describe|cut -c2-)

            snapcraftctl set-version $version
            snapcraftctl build

            mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications \
                $SNAPCRAFT_PART_INSTALL/usr/share/icons

            cp extra/linux/Alacritty.desktop $SNAPCRAFT_PART_INSTALL/usr/share/applications/Alacritty.desktop
            cp extra/logo/compat/alacritty-term+scanlines.png $SNAPCRAFT_PART_INSTALL/usr/share/icons/Alacritty.png

            sed -i 's|Icon=.*|Icon=${SNAP}/usr/share/icons/Alacritty.png|g' \
                $SNAPCRAFT_PART_INSTALL/usr/share/applications/Alacritty.desktop
