name: alacritty
adopt-info: alacritty

base: core20
grade: stable
confinement: classic

apps:
    alacritty:
        command: bin/alacritty
        common-id: io.alacritty.Alacritty
        desktop: usr/share/applications/Alacritty.desktop

parts:
    alacritty:
        plugin: rust
        source: https://github.com/alacritty/alacritty/archive/v0.6.0.tar.gz
        parse-info:
            - extra/linux/io.alacritty.Alacritty.appdata.xml
        rust-path:
            - alacritty
        build-packages:
            - cmake
            - pkg-config
            - libfreetype6-dev
            - libfontconfig1-dev
            - libxcb-xfixes0-dev
            - python3
            - libegl1-mesa-dev # necessary for nvidia users on wayland
        override-build: |
            snapcraftctl build

            mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications \
                $SNAPCRAFT_PART_INSTALL/usr/share/icons

            cp extra/linux/Alacritty.desktop $SNAPCRAFT_PART_INSTALL/usr/share/applications/Alacritty.desktop
            cp extra/logo/compat/alacritty-term+scanlines.png $SNAPCRAFT_PART_INSTALL/usr/share/icons/Alacritty.png

            sed -i 's|Icon=.*|Icon=${SNAP}/usr/share/icons/Alacritty.png|g' \
                $SNAPCRAFT_PART_INSTALL/usr/share/applications/Alacritty.desktop
